### ISSUE TITLE
wrong example  for Docker

### ISSUE THREAD

**Issue by rcemper** [mwaseem75/iris-geo-map#1]
in README:
Run below command to import Synthetic Medical Data dataset by passing dataset ID(1)
**do ##class(dc.irisgeomap.folium).MyLocation(1)**

Wrong class name + method doesn't accept params
only this works
**do ##class(dc.IrisGeoMap.Folium).MyLocation()**

_latitude = 44.933143, longitude = 7.540121_  

Wherever that might be.   SW from Torino(IT),  a location named "NONE"   
its a param error .  I place a PR to fix it

**Comment by mwaseem75** [comment]
Issue is resolved. Thanks
