### ISSUE TITLE
No link to see the map

### ISSUE THREAD

**Issue by rcemper** [mwaseem75/iris-geo-map#2]
I expected to see the map from the screenshot
But there is no URL or similar.

**Comment by rcemper** [comment]
I just realized that csp directory is missing from module.xml and NOT installed

**Comment by rcemper** [comment]
I found id from setup reverse , but it is missing in README,md
````
###### show the maps by this link
http://localhost:52773/csp/irisgeomap/index.csp
````

**Comment by mwaseem75** [comment]
Online demo and link is added
